services:
  robot1:
    extends:
      file: common.yml
      service: robot
    container_name: robot1
    networks:
      mymacvlan:
        ipv4_address: 10.0.2.1
  robot2:
    extends:
      file: common.yml
      service: robot
    container_name: robot2 
    networks:
      mymacvlan:
        ipv4_address: 10.0.2.2 
  robot3:
    extends:
      file: common.yml
      service: robot
    container_name: robot3 
    networks:
      mymacvlan:
        ipv4_address: 10.0.2.3 
networks:
  mymacvlan:
    name: my-macvlan-net
    driver: macvlan
    driver_opts:
      parent: ${NETWORK_INTERFACE:?err}
    ipam:
      config:
        - subnet: "10.0.1.0/16"
          gateway: "10.0.1.1"
