services:
  robot1:
    extends:
      file: common.yml
      service: robot_base
    container_name: ${CONTAINER_NAME:?err}
    networks:
      mymacvlan:
        ipv4_address: ${CONTAINER_IP:?err}
networks:
  mymacvlan:
    name: my-macvlan-net
    driver: macvlan
    driver_opts:
      parent: ${NETWORK_INTERFACE:?err}
    ipam:
      config:
        - subnet: "10.0.1.0/16"
          gateway: "10.0.1.1"
