networks:
  mymacvlan:
    name: my-macvlan-net
    #####
    # For running multiple robots across different computers
    # driver: macvlan
    # For running multiple robots on the same computer
    driver: bridge
    #####
    driver_opts:
      parent: ${NETWORK_INTERFACE:?err}
    ipam:
      config:
        - subnet: "10.0.1.0/16"
          gateway: "10.0.1.1"
